import 'package:flutter/material.dart';

class RibnColors {
  RibnColors._();
  static const Color primary = Color(0xFF144C5F);
  static const Color primaryOffColor = Color(0xFF155464);
  static const Color accent = Color(0xFF175F6B);
  static const Color secondary = Color(0xFF86DFCC);
  static const Color secondaryDark = Color(0xFF18CCAB);
  static const Color tertiary = Color(0xFF259E95);
  static const Color defaultText = Color(0xFF323232);
  static const Color greyText = Color(0xFF979797);
  static const Color inactive = Color(0xFF7795A0);
  static const Color active = Color(0xFF8AE3CF);
  static const Color lightGrey = Color(0xFFEEEEEE);
  static const Color background = Color(0xFFF8F8F8);
  static const Color whiteBackground = Color(0xfffefefe);
  static const Color hintTextColor = Color(0xffbcbcbc);
  static const Color greyedOut = Color(0xff585858);
  static const Color primaryButtonHover = Color(0xFF2c5e6f);
  static const Color secondaryButtonHover = Color(0xFF92e2d1);
  static const Color primaryButtonShadow = Color(0x4D16586E);
  static const Color secondaryButtonShadow = Color(0x4D87E2CE);
  static const Color whiteButtonShadow = Color(0x4D8AE3CF);
  static const Color ghostButtonText = Color(0xFF979797);
  static const Color assetCardShadow = Color(0x80E2ECF9);
  static const Color assetCardHoverColor = Color(0xFFFBFCFC);
  static const Color blackShadow = Color(0x0D000000);
  static const Color greyShadow = Color(0x80E2ECF9);
  static const Color lightGreyTitle = Color(0xFFE5E5E5);
  static const Color greyTransparent = Color(0x33979797);
  static const Color transparentGreyText = Color(0x73FFFFFF);
  static const Color transparentAlternateGreyText = Color(0x40FFFFFF);
  static const Color transparentPrimary = Color(0x73144C5F);
  static const Color statusChipGrey = Color(0x4DDADADA);
  static const Color statusChipYellow = Color(0xffFEE909);
  static const Color statusChipGreen = Color(0xff70FF00);
  static const Color statusChipRed = Color(0xffFF6464);
  static const Color lightGreyDivider = Color(0xffCCD0D7);
}
