/// Enums options used to pass through to new CustomText widget for applying hierarchical styles

enum TextTagOptions {
  h1,
  h2,
  h3,
  h4,
  h5,
  bodyExtraLarge,
  bodyExtraLargeMedium,
  bodyExtraLargeBold,
  bodyExtraLargeSpacedOut,
  bodyLarge,
  bodyLargeMedium,
  bodyLargeBold,
  bodyLargeSpacedOut,
  bodyRegular,
  bodyRegularMedium,
  bodyRegularBold,
  bodyRegularSpacedOut,
  bodySmall,
  bodySmallMedium,
  bodySmallBold,
  bodySmallSpacedOut,
  bodyExtraSmall,
  bodyExtraSmallMedium,
  bodyExtraSmallBold,
  bodyExtraSmallSpacedOut,
}
